"""added color attribute to Planet model

Revision ID: 929de86a0268
Revises: 5c82b138acfb
Create Date: 2022-10-31 13:06:16.224166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929de86a0268'
down_revision = '5c82b138acfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'color')
    # ### end Alembic commands ###
